# Generated by Django 3.2.9 on 2021-11-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='user',
        ),
    ]
