# Generated by Django 3.2.9 on 2021-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_remove_gamecategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='rating',
        ),
        migrations.AddField(
            model_name='games',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', through='raterapi.GameReviews', to='raterapi.Player'),
        ),
    ]
