# Generated by Django 3.2.9 on 2021-11-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_auto_20211109_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='gamereviews',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='raterapi.games'),
        ),
    ]
