# Generated by Django 3.2.9 on 2021-11-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0004_auto_20211109_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='raterapi.games'),
        ),
    ]
